### ISSUE TITLE
Unable to execute "Render Video" Github Actions workflow

### ISSUE THREAD

**Issue by pascaloliv** [remotion-dev/template-helloworld#5]
Hello everyone !

It seems recent commits :   
- https://github.com/remotion-dev/template-helloworld/commit/ed65487d5048537aacf5c3f3810dd91f814f2dfd
- https://github.com/remotion-dev/template-helloworld/commit/70d0ff3fec07c8cd59e40e92e147bf2c4e1f8348
- https://github.com/remotion-dev/template-helloworld/commit/bd23807f273cbb3498de7a4424eefeda85b22603

Broke the Render Video Github Actions workflow.
It looks like that the parsing of the `$WORKFLOW_INPUT` is broken.

<img width="1447" alt="Capture d’écran 2021-12-11 à 19 50 19" src="https://user-images.githubusercontent.com/442681/145688156-6b813cfe-90ee-4931-830e-373da3114e68.png">

<img width="1121" alt="error-workflow" src="https://user-images.githubusercontent.com/442681/145688159-86be304f-2b46-47e6-913e-d264fa05283a.png">

**Comment by JonnyBurger** [comment]
Sorry for the late response! It went under my radar. I noticed the bug as well, GitHub made a change apparently, I'll merge and update all these templates in the next day or two!

**Comment by tribakzero** [comment]
Had this problem, this is how I fixed it. It should be a thing to copy/paste it to each repo:
```
      - run: npm run build -- --props=$WORKFLOW_INPUT
        env:
          WORKFLOW_INPUT: ${{ inputs }}
```

**Comment by tribakzero** [comment]
My currently working solution, had to move name to the top or github would ignore the workflow:
```
name: Render video

on:
  workflow_dispatch:
    inputs:
      ...

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run build -- --props='$WORKFLOW_INPUT'
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4
```
